### ISSUE TITLE
無法進入遊戲

### ISSUE THREAD

**Issue by WaKaWeak** [xuancat0208/MinecraftCatPawServer#1]
會卡在正在載入地形... 然後就沒有畫面
先前有刪除過一次.minecraft資料夾
當時可以進入 不過會卡在藍天白雲然後無法移動及說話

**Comment by WaKaWeak** [comment]
[https://i.imgur.com/PsYVpWF.png](url)

**Comment by xuancat0208** [comment]
此問題已經在早上緊急修復, 瘋狂重登或是登入到一半直接關閉遊戲即可修正此BUG
